language: csharp
solution: ASI.sln
install:
  - nuget restore ASI.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ASI.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./ASI.Tests/bin/Release/ASI.Tests.dll
