/*
 * ASI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/20/2017
 */
using System;
using ASI.PCL.Controllers;
using ASI.PCL.Http.Client;

namespace ASI.PCL
{
    public partial class ASIClient
    {

        /// <summary>
        /// Singleton access to ASIESPLookupsInfantToddler controller
        /// </summary>
        public ASIESPLookupsInfantToddlerController ASIESPLookupsInfantToddler
        {
            get
            {
                return ASIESPLookupsInfantToddlerController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsPants controller
        /// </summary>
        public ASIESPLookupsPantsController ASIESPLookupsPants
        {
            get
            {
                return ASIESPLookupsPantsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookups controller
        /// </summary>
        public ASIESPLookupsController ASIESPLookups
        {
            get
            {
                return ASIESPLookupsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsCategories controller
        /// </summary>
        public ASIESPLookupsCategoriesController ASIESPLookupsCategories
        {
            get
            {
                return ASIESPLookupsCategoriesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPCarrier controller
        /// </summary>
        public ASIESPCarrierController ASIESPCarrier
        {
            get
            {
                return ASIESPCarrierController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsColors controller
        /// </summary>
        public ASIESPLookupsColorsController ASIESPLookupsColors
        {
            get
            {
                return ASIESPLookupsColorsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsMaterials controller
        /// </summary>
        public ASIESPLookupsMaterialsController ASIESPLookupsMaterials
        {
            get
            {
                return ASIESPLookupsMaterialsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsBra controller
        /// </summary>
        public ASIESPLookupsBraController ASIESPLookupsBra
        {
            get
            {
                return ASIESPLookupsBraController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsDressShirtDressShirt controller
        /// </summary>
        public ASIESPLookupsDressShirtDressShirtController ASIESPLookupsDressShirtDressShirt
        {
            get
            {
                return ASIESPLookupsDressShirtDressShirtController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsHoisery controller
        /// </summary>
        public ASIESPLookupsHoiseryController ASIESPLookupsHoisery
        {
            get
            {
                return ASIESPLookupsHoiseryController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsSafetyWarning controller
        /// </summary>
        public ASIESPLookupsSafetyWarningController ASIESPLookupsSafetyWarning
        {
            get
            {
                return ASIESPLookupsSafetyWarningController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPLookupsReservedRestricted controller
        /// </summary>
        public ASIESPLookupsReservedRestrictedController ASIESPLookupsReservedRestricted
        {
            get
            {
                return ASIESPLookupsReservedRestrictedController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ASIESPUpchargeLevels controller
        /// </summary>
        public ASIESPUpchargeLevelsController ASIESPUpchargeLevels
        {
            get
            {
                return ASIESPUpchargeLevelsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MiscLogin controller
        /// </summary>
        public MiscLoginController MiscLogin
        {
            get
            {
                return MiscLoginController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Misc controller
        /// </summary>
        public MiscController Misc
        {
            get
            {
                return MiscController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public ASIClient() { }
    }
}