/*
 * ASI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/20/2017
 */
using ASI.PCL.Http.Client;
using ASI.PCL.Http.Request;
using ASI.PCL.Http.Response;

namespace ASI.Tests.Helpers
{
    public class HttpCallBackEventsHandler
    {
        public HttpRequest Request { get; private set; }

        public HttpResponse Response { get; private set; }

        public void OnBeforeHttpRequestEventHandler(IHttpClient source, HttpRequest request)
        {
            this.Request = request;
        }

        public void OnAfterHttpResponseEventHandler(IHttpClient source, HttpResponse response)
        {
            this.Response = response;
        }
    }
}
