/*
 * ASI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using ASI.PCL;
using ASI.PCL.Utilities; 
using ASI.PCL.Http.Client;
using ASI.PCL.Http.Response;
using ASI.Tests.Helpers;
using NUnit.Framework;
using ASI.PCL;
using ASI.PCL.Controllers;
using ASI.PCL.Exceptions;

namespace ASI.Tests
{
    [TestFixture]
    public class ASIESPLookupsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static ASIESPLookupsController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().ASIESPLookups;
        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestStandardNumbered1() 
        {

            // Perform API call

            try
            {
                await controller.GetStandardNumberedAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestVolumeWeight1() 
        {

            // Perform API call

            try
            {
                await controller.GetVolumeWeightAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestCapacity1() 
        {

            // Perform API call

            try
            {
                await controller.GetCapacityAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestOther1() 
        {

            // Perform API call

            try
            {
                await controller.GetOtherAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestDimension1() 
        {

            // Perform API call

            try
            {
                await controller.GetDimensionAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestShapes1() 
        {

            // Perform API call

            try
            {
                await controller.GetShapesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestThemes1() 
        {

            // Perform API call

            try
            {
                await controller.GetThemes1Async();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestPackages1() 
        {

            // Perform API call

            try
            {
                await controller.GetPackagesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestCompliances1() 
        {

            // Perform API call

            try
            {
                await controller.GetCompliancesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestWarranty1() 
        {

            // Perform API call

            try
            {
                await controller.GetWarrantyAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestBattery1() 
        {

            // Perform API call

            try
            {
                await controller.GetBatteryAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestItemWeight1() 
        {

            // Perform API call

            try
            {
                await controller.GetItemWeightAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestShippingWeight1() 
        {

            // Perform API call

            try
            {
                await controller.GetShippingWeightAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestAvailabilityCriterias1() 
        {

            // Perform API call

            try
            {
                await controller.GetAvailabilityCriteriasAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestUpchargeTypes1() 
        {

            // Perform API call

            try
            {
                await controller.GetUpchargeTypesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestDiscountRates1() 
        {

            // Perform API call

            try
            {
                await controller.GetDiscountRatesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestCurrencies1() 
        {

            // Perform API call

            try
            {
                await controller.GetCurrenciesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestPriceModifiers1() 
        {

            // Perform API call

            try
            {
                await controller.GetPriceModifiersAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestSelectedLineNames1() 
        {

            // Perform API call

            try
            {
                await controller.GetSelectedLineNamesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestFOBPoints1() 
        {

            // Perform API call

            try
            {
                await controller.GetFOBPointsAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestOrigins1() 
        {

            // Perform API call

            try
            {
                await controller.GetOriginsAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestImprintMethods1() 
        {

            // Perform API call

            try
            {
                await controller.GetImprintMethodsAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestPersonalization1() 
        {

            // Perform API call

            try
            {
                await controller.GetPersonalizationAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestArtworks1() 
        {

            // Perform API call

            try
            {
                await controller.GetArtworksAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestCriteriaCodes1() 
        {

            // Perform API call

            try
            {
                await controller.GetCriteriaCodesAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestBasePriceCriterias1() 
        {

            // Perform API call

            try
            {
                await controller.GetBasePriceCriteriasAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestUpchargeCriterias1() 
        {

            // Perform API call

            try
            {
                await controller.GetUpchargeCriteriasAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestProductNumberCriterias1() 
        {

            // Perform API call

            try
            {
                await controller.GetProductNumberCriteriasAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestShippingDimension1() 
        {

            // Perform API call

            try
            {
                await controller.GetShippingDimensionAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestShippingEstimate1() 
        {

            // Perform API call

            try
            {
                await controller.GetShippingEstimateAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestMediaCiatations1() 
        {

            // Perform API call

            try
            {
                await controller.GetMediaCiatationsAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

    }
}