/*
 * ASI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using ASI.PCL;
using ASI.PCL.Utilities; 
using ASI.PCL.Http.Client;
using ASI.PCL.Http.Response;
using ASI.Tests.Helpers;
using NUnit.Framework;
using ASI.PCL;
using ASI.PCL.Controllers;
using ASI.PCL.Exceptions;

namespace ASI.Tests
{
    [TestFixture]
    public class ASIESPLookupsSafetyWarningControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static ASIESPLookupsSafetyWarningController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().ASIESPLookupsSafetyWarning;
        }

        /// <summary>
        /// TODO: Add Description 
        /// </summary>
        [Test]
        public async Task TestSafetyWarnings1() 
        {

            // Perform API call

            try
            {
                await controller.GetSafetyWarningsAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

    }
}